name: GalaxyGal
favicon: null
layout_spectrum: 0.32883
typography_spectrum: 0.25676
title: Welcome to My Universe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54276545-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080202'
    - '#e2d4b7'
    - '#4f3c2d'
    - '#80684c'
    - '#b5a488'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
