analytics:
  google: UA-54276545-2
color:
  brandColors:
    - '#080202'
    - '#e2d4b7'
    - '#4f3c2d'
    - '#80684c'
    - '#b5a488'
  brandStrength: 0.1875
  lightness: 0.600507
  rhythmicContrast: 0.75
  saturation: 0.1875
cta: {}
layout_spectrum: 0.943412
name: GalaxyGal
opengraph: {}
purpose: []
typography_spectrum: 0.17502
