name: GalaxyGal
favicon: null
layout_spectrum: 0.1021679483819753
typography_spectrum: 0.7474769614636898
title: 'What Smart Guys Need to Know about Work, Women and Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.49372326978482306
  lightness: 0.8329924186691642
  saturation: 0.13176248758099973
  rhythmicContrast: 0.8762217278126627
purpose: []
