name: GalaxyGal
favicon: null
layout_spectrum: 0.44011
typography_spectrum: 0.17502
title: 'What Smart Guys Need to Know about Work, Women and Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080202'
    - '#e2d4b7'
    - '#4f3c2d'
    - '#80684c'
    - '#b5a488'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
